// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: example.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GlobalEnum1 Description
type GlobalEnum1 int32

const (
	GlobalEnum1_GlobalEnumVal   GlobalEnum1 = 0 // field 0 desc
	GlobalEnum1_GlobalEnumVal1  GlobalEnum1 = 1 // field 1 desc
	GlobalEnum1_GlobalEnumVal11 GlobalEnum1 = 1 // field 111 desc
	GlobalEnum1_GlobalEnumVal12 GlobalEnum1 = 1 // field 12 different description with **bold**
	GlobalEnum1_GlobalEnumVal2  GlobalEnum1 = 2 // field 2 desc
	GlobalEnum1_GlobalEnumVal3  GlobalEnum1 = 3 // field 3 *desc*
)

// Enum value maps for GlobalEnum1.
var (
	GlobalEnum1_name = map[int32]string{
		0: "GlobalEnumVal",
		1: "GlobalEnumVal1",
		// Duplicate value: 1: "GlobalEnumVal11",
		// Duplicate value: 1: "GlobalEnumVal12",
		2: "GlobalEnumVal2",
		3: "GlobalEnumVal3",
	}
	GlobalEnum1_value = map[string]int32{
		"GlobalEnumVal":   0,
		"GlobalEnumVal1":  1,
		"GlobalEnumVal11": 1,
		"GlobalEnumVal12": 1,
		"GlobalEnumVal2":  2,
		"GlobalEnumVal3":  3,
	}
)

func (x GlobalEnum1) Enum() *GlobalEnum1 {
	p := new(GlobalEnum1)
	*p = x
	return p
}

func (x GlobalEnum1) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GlobalEnum1) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[0].Descriptor()
}

func (GlobalEnum1) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[0]
}

func (x GlobalEnum1) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GlobalEnum1.Descriptor instead.
func (GlobalEnum1) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

// EnumAllowingAlias description
type ExampleMessage2_EnumAllowingAlias int32

const (
	ExampleMessage2_UNKNOWN ExampleMessage2_EnumAllowingAlias = 0 // unknown field desc
	ExampleMessage2_STARTED ExampleMessage2_EnumAllowingAlias = 1 // started field desc.
	ExampleMessage2_RUNNING ExampleMessage2_EnumAllowingAlias = 1 // running field description
)

// Enum value maps for ExampleMessage2_EnumAllowingAlias.
var (
	ExampleMessage2_EnumAllowingAlias_name = map[int32]string{
		0: "UNKNOWN",
		1: "STARTED",
		// Duplicate value: 1: "RUNNING",
	}
	ExampleMessage2_EnumAllowingAlias_value = map[string]int32{
		"UNKNOWN": 0,
		"STARTED": 1,
		"RUNNING": 1,
	}
)

func (x ExampleMessage2_EnumAllowingAlias) Enum() *ExampleMessage2_EnumAllowingAlias {
	p := new(ExampleMessage2_EnumAllowingAlias)
	*p = x
	return p
}

func (x ExampleMessage2_EnumAllowingAlias) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExampleMessage2_EnumAllowingAlias) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[1].Descriptor()
}

func (ExampleMessage2_EnumAllowingAlias) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[1]
}

func (x ExampleMessage2_EnumAllowingAlias) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExampleMessage2_EnumAllowingAlias.Descriptor instead.
func (ExampleMessage2_EnumAllowingAlias) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1, 0}
}

type ExampleMessage2_EnumAllowingAlias2 int32

const (
	ExampleMessage2_UNKNOWN2 ExampleMessage2_EnumAllowingAlias2 = 0
	ExampleMessage2_STARTED2 ExampleMessage2_EnumAllowingAlias2 = 1
)

// Enum value maps for ExampleMessage2_EnumAllowingAlias2.
var (
	ExampleMessage2_EnumAllowingAlias2_name = map[int32]string{
		0: "UNKNOWN2",
		1: "STARTED2",
	}
	ExampleMessage2_EnumAllowingAlias2_value = map[string]int32{
		"UNKNOWN2": 0,
		"STARTED2": 1,
	}
)

func (x ExampleMessage2_EnumAllowingAlias2) Enum() *ExampleMessage2_EnumAllowingAlias2 {
	p := new(ExampleMessage2_EnumAllowingAlias2)
	*p = x
	return p
}

func (x ExampleMessage2_EnumAllowingAlias2) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExampleMessage2_EnumAllowingAlias2) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[2].Descriptor()
}

func (ExampleMessage2_EnumAllowingAlias2) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[2]
}

func (x ExampleMessage2_EnumAllowingAlias2) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExampleMessage2_EnumAllowingAlias2.Descriptor instead.
func (ExampleMessage2_EnumAllowingAlias2) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1, 1}
}

type ExampleMessage2_NestedMessage_NestedNestedEnum int32

const (
	ExampleMessage2_NestedMessage_NestedNestedValue  ExampleMessage2_NestedMessage_NestedNestedEnum = 0
	ExampleMessage2_NestedMessage_NestedNestedValue1 ExampleMessage2_NestedMessage_NestedNestedEnum = 1
)

// Enum value maps for ExampleMessage2_NestedMessage_NestedNestedEnum.
var (
	ExampleMessage2_NestedMessage_NestedNestedEnum_name = map[int32]string{
		0: "NestedNestedValue",
		1: "NestedNestedValue1",
	}
	ExampleMessage2_NestedMessage_NestedNestedEnum_value = map[string]int32{
		"NestedNestedValue":  0,
		"NestedNestedValue1": 1,
	}
)

func (x ExampleMessage2_NestedMessage_NestedNestedEnum) Enum() *ExampleMessage2_NestedMessage_NestedNestedEnum {
	p := new(ExampleMessage2_NestedMessage_NestedNestedEnum)
	*p = x
	return p
}

func (x ExampleMessage2_NestedMessage_NestedNestedEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExampleMessage2_NestedMessage_NestedNestedEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_example_proto_enumTypes[3].Descriptor()
}

func (ExampleMessage2_NestedMessage_NestedNestedEnum) Type() protoreflect.EnumType {
	return &file_example_proto_enumTypes[3]
}

func (x ExampleMessage2_NestedMessage_NestedNestedEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExampleMessage2_NestedMessage_NestedNestedEnum.Descriptor instead.
func (ExampleMessage2_NestedMessage_NestedNestedEnum) EnumDescriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1, 0, 0}
}

// ExampleMessage1 - Example Leading Comment for ExampleMessage1
type ExampleMessage1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyString string `protobuf:"bytes,1,opt,name=MyString,proto3" json:"MyString,omitempty"`
}

func (x *ExampleMessage1) Reset() {
	*x = ExampleMessage1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleMessage1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleMessage1) ProtoMessage() {}

func (x *ExampleMessage1) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleMessage1.ProtoReflect.Descriptor instead.
func (*ExampleMessage1) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleMessage1) GetMyString() string {
	if x != nil {
		return x.MyString
	}
	return ""
}

// ExampleMessage2 - Example Leading Comment for ExampleMessage2
// [Example]{
// "MyInt": 12,
// "aliased": 1,
// "aliased2": 1,
// "global_enum": 0,
// "repeated_global_enum": [1, 0, 1, 0],
// "optional_global_enum": 1,
// "nested_message": {
// "v": 1
// },
// "nested_nested_enum": 1
// }
type ExampleMessage2 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MyInt              int32                                          `protobuf:"varint,1,opt,name=MyInt,proto3" json:"MyInt,omitempty"`
	Nested             *ExampleMessage2_ExampleNested                 `protobuf:"bytes,2,opt,name=nested,proto3" json:"nested,omitempty"`
	Aliased            ExampleMessage2_EnumAllowingAlias              `protobuf:"varint,3,opt,name=aliased,proto3,enum=v1.ExampleMessage2_EnumAllowingAlias" json:"aliased,omitempty"`
	Aliased2           ExampleMessage2_EnumAllowingAlias2             `protobuf:"varint,4,opt,name=aliased2,proto3,enum=v1.ExampleMessage2_EnumAllowingAlias2" json:"aliased2,omitempty"`
	GlobalEnum         GlobalEnum1                                    `protobuf:"varint,5,opt,name=global_enum,json=globalEnum,proto3,enum=v1.GlobalEnum1" json:"global_enum,omitempty"`
	RepeatedGlobalEnum []GlobalEnum1                                  `protobuf:"varint,6,rep,packed,name=repeated_global_enum,json=repeatedGlobalEnum,proto3,enum=v1.GlobalEnum1" json:"repeated_global_enum,omitempty"`
	OptionalGlobalEnum *GlobalEnum1                                   `protobuf:"varint,7,opt,name=optional_global_enum,json=optionalGlobalEnum,proto3,enum=v1.GlobalEnum1,oneof" json:"optional_global_enum,omitempty"`
	NestedMessage      *ExampleMessage2_NestedMessage                 `protobuf:"bytes,8,opt,name=nested_message,json=nestedMessage,proto3" json:"nested_message,omitempty"`
	NestedNestedEnum   ExampleMessage2_NestedMessage_NestedNestedEnum `protobuf:"varint,9,opt,name=nested_nested_enum,json=nestedNestedEnum,proto3,enum=v1.ExampleMessage2_NestedMessage_NestedNestedEnum" json:"nested_nested_enum,omitempty"`
}

func (x *ExampleMessage2) Reset() {
	*x = ExampleMessage2{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleMessage2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleMessage2) ProtoMessage() {}

func (x *ExampleMessage2) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleMessage2.ProtoReflect.Descriptor instead.
func (*ExampleMessage2) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *ExampleMessage2) GetMyInt() int32 {
	if x != nil {
		return x.MyInt
	}
	return 0
}

func (x *ExampleMessage2) GetNested() *ExampleMessage2_ExampleNested {
	if x != nil {
		return x.Nested
	}
	return nil
}

func (x *ExampleMessage2) GetAliased() ExampleMessage2_EnumAllowingAlias {
	if x != nil {
		return x.Aliased
	}
	return ExampleMessage2_UNKNOWN
}

func (x *ExampleMessage2) GetAliased2() ExampleMessage2_EnumAllowingAlias2 {
	if x != nil {
		return x.Aliased2
	}
	return ExampleMessage2_UNKNOWN2
}

func (x *ExampleMessage2) GetGlobalEnum() GlobalEnum1 {
	if x != nil {
		return x.GlobalEnum
	}
	return GlobalEnum1_GlobalEnumVal
}

func (x *ExampleMessage2) GetRepeatedGlobalEnum() []GlobalEnum1 {
	if x != nil {
		return x.RepeatedGlobalEnum
	}
	return nil
}

func (x *ExampleMessage2) GetOptionalGlobalEnum() GlobalEnum1 {
	if x != nil && x.OptionalGlobalEnum != nil {
		return *x.OptionalGlobalEnum
	}
	return GlobalEnum1_GlobalEnumVal
}

func (x *ExampleMessage2) GetNestedMessage() *ExampleMessage2_NestedMessage {
	if x != nil {
		return x.NestedMessage
	}
	return nil
}

func (x *ExampleMessage2) GetNestedNestedEnum() ExampleMessage2_NestedMessage_NestedNestedEnum {
	if x != nil {
		return x.NestedNestedEnum
	}
	return ExampleMessage2_NestedMessage_NestedNestedValue
}

// ReturnType - Empty Structure Placeholder
type ReturnType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReturnType) Reset() {
	*x = ReturnType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnType) ProtoMessage() {}

func (x *ReturnType) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnType.ProtoReflect.Descriptor instead.
func (*ReturnType) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{2}
}

type ExampleMessage2_NestedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V ExampleMessage2_NestedMessage_NestedNestedEnum `protobuf:"varint,1,opt,name=v,proto3,enum=v1.ExampleMessage2_NestedMessage_NestedNestedEnum" json:"v,omitempty"`
}

func (x *ExampleMessage2_NestedMessage) Reset() {
	*x = ExampleMessage2_NestedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleMessage2_NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleMessage2_NestedMessage) ProtoMessage() {}

func (x *ExampleMessage2_NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleMessage2_NestedMessage.ProtoReflect.Descriptor instead.
func (*ExampleMessage2_NestedMessage) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ExampleMessage2_NestedMessage) GetV() ExampleMessage2_NestedMessage_NestedNestedEnum {
	if x != nil {
		return x.V
	}
	return ExampleMessage2_NestedMessage_NestedNestedValue
}

// MyInt - Example trailing Comment
type ExampleMessage2_ExampleNested struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ExampleMessage2_ExampleNested) Reset() {
	*x = ExampleMessage2_ExampleNested{}
	if protoimpl.UnsafeEnabled {
		mi := &file_example_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleMessage2_ExampleNested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleMessage2_ExampleNested) ProtoMessage() {}

func (x *ExampleMessage2_ExampleNested) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleMessage2_ExampleNested.ProtoReflect.Descriptor instead.
func (*ExampleMessage2_ExampleNested) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ExampleMessage2_ExampleNested) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_example_proto protoreflect.FileDescriptor

var file_example_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x76, 0x31, 0x22, 0x2d, 0x0a, 0x0f, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x79, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d, 0x79, 0x53, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x22, 0x97, 0x07, 0x0a, 0x0f, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x79, 0x49, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x79, 0x49, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x06,
	0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x76,
	0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x32, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x52,
	0x06, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x3f, 0x0a, 0x07, 0x61, 0x6c, 0x69, 0x61, 0x73,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x2e, 0x45, 0x6e,
	0x75, 0x6d, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x52,
	0x07, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x12, 0x42, 0x0a, 0x08, 0x61, 0x6c, 0x69, 0x61,
	0x73, 0x65, 0x64, 0x32, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x2e,
	0x45, 0x6e, 0x75, 0x6d, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e, 0x67, 0x41, 0x6c, 0x69, 0x61,
	0x73, 0x32, 0x52, 0x08, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x65, 0x64, 0x32, 0x12, 0x30, 0x0a, 0x0b,
	0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75,
	0x6d, 0x31, 0x52, 0x0a, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x41,
	0x0a, 0x14, 0x72, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x31, 0x52, 0x12, 0x72,
	0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75,
	0x6d, 0x12, 0x46, 0x0a, 0x14, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x5f, 0x67, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x31,
	0x48, 0x00, 0x52, 0x12, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x48, 0x0a, 0x0e, 0x6e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x60, 0x0a, 0x12, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x5f, 0x6e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x32, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x45,
	0x6e, 0x75, 0x6d, 0x52, 0x10, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74, 0x65,
	0x64, 0x45, 0x6e, 0x75, 0x6d, 0x1a, 0x94, 0x01, 0x0a, 0x0d, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x01, 0x76, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x32, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74,
	0x65, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x01, 0x76, 0x22, 0x41, 0x0a, 0x10, 0x4e, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x15, 0x0a,
	0x11, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4e, 0x65,
	0x73, 0x74, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x31, 0x10, 0x01, 0x1a, 0x23, 0x0a, 0x0d,
	0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x3e, 0x0a, 0x11, 0x45, 0x6e, 0x75, 0x6d, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e,
	0x67, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x1a, 0x02, 0x10,
	0x01, 0x22, 0x30, 0x0a, 0x12, 0x45, 0x6e, 0x75, 0x6d, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x69, 0x6e,
	0x67, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x32, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x32, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44,
	0x32, 0x10, 0x01, 0x42, 0x17, 0x0a, 0x15, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c,
	0x5f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x22, 0x0c, 0x0a, 0x0a,
	0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x8a, 0x01, 0x0a, 0x0b, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x31, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x6c,
	0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x12, 0x0a,
	0x0e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x31, 0x10,
	0x01, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x56,
	0x61, 0x6c, 0x31, 0x31, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x31, 0x32, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x47,
	0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c, 0x32, 0x10, 0x02, 0x12,
	0x12, 0x0a, 0x0e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x61, 0x6c,
	0x33, 0x10, 0x03, 0x1a, 0x02, 0x10, 0x01, 0x32, 0x7e, 0x0a, 0x0e, 0x45, 0x78, 0x61, 0x6d, 0x70,
	0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x45, 0x78, 0x61,
	0x6d, 0x70, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x31, 0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x31, 0x1a, 0x0e,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x00,
	0x12, 0x35, 0x0a, 0x0c, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x32,
	0x12, 0x13, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x1a, 0x0e, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x2e, 0x67,
	0x65, 0x6e, 0x64, 0x6f, 0x63, 0x75, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x6e, 0x64, 0x6f,
	0x63, 0x75, 0x2f, 0x57, 0x69, 0x74, 0x68, 0x45, 0x6e, 0x75, 0x6d, 0x2e, 0x67, 0x69, 0x74, 0x2f,
	0x73, 0x64, 0x6b, 0x2f, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData = file_example_proto_rawDesc
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_example_proto_rawDescData)
	})
	return file_example_proto_rawDescData
}

var file_example_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_example_proto_goTypes = []interface{}{
	(GlobalEnum1)(0),                                    // 0: v1.GlobalEnum1
	(ExampleMessage2_EnumAllowingAlias)(0),              // 1: v1.ExampleMessage2.EnumAllowingAlias
	(ExampleMessage2_EnumAllowingAlias2)(0),             // 2: v1.ExampleMessage2.EnumAllowingAlias2
	(ExampleMessage2_NestedMessage_NestedNestedEnum)(0), // 3: v1.ExampleMessage2.NestedMessage.NestedNestedEnum
	(*ExampleMessage1)(nil),                             // 4: v1.ExampleMessage1
	(*ExampleMessage2)(nil),                             // 5: v1.ExampleMessage2
	(*ReturnType)(nil),                                  // 6: v1.ReturnType
	(*ExampleMessage2_NestedMessage)(nil),               // 7: v1.ExampleMessage2.NestedMessage
	(*ExampleMessage2_ExampleNested)(nil),               // 8: v1.ExampleMessage2.ExampleNested
}
var file_example_proto_depIdxs = []int32{
	8,  // 0: v1.ExampleMessage2.nested:type_name -> v1.ExampleMessage2.ExampleNested
	1,  // 1: v1.ExampleMessage2.aliased:type_name -> v1.ExampleMessage2.EnumAllowingAlias
	2,  // 2: v1.ExampleMessage2.aliased2:type_name -> v1.ExampleMessage2.EnumAllowingAlias2
	0,  // 3: v1.ExampleMessage2.global_enum:type_name -> v1.GlobalEnum1
	0,  // 4: v1.ExampleMessage2.repeated_global_enum:type_name -> v1.GlobalEnum1
	0,  // 5: v1.ExampleMessage2.optional_global_enum:type_name -> v1.GlobalEnum1
	7,  // 6: v1.ExampleMessage2.nested_message:type_name -> v1.ExampleMessage2.NestedMessage
	3,  // 7: v1.ExampleMessage2.nested_nested_enum:type_name -> v1.ExampleMessage2.NestedMessage.NestedNestedEnum
	3,  // 8: v1.ExampleMessage2.NestedMessage.v:type_name -> v1.ExampleMessage2.NestedMessage.NestedNestedEnum
	4,  // 9: v1.ExampleService.ExampleCall1:input_type -> v1.ExampleMessage1
	5,  // 10: v1.ExampleService.ExampleCall2:input_type -> v1.ExampleMessage2
	6,  // 11: v1.ExampleService.ExampleCall1:output_type -> v1.ReturnType
	6,  // 12: v1.ExampleService.ExampleCall2:output_type -> v1.ReturnType
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleMessage1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleMessage2); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleMessage2_NestedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_example_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleMessage2_ExampleNested); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_example_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_example_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		EnumInfos:         file_example_proto_enumTypes,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_rawDesc = nil
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
