/* eslint-disable */
/*Generated by GenDocu.com*/
// package: v1
// file: example.proto

var example_pb = require("./example_pb");
var grpc = require("@improbable-eng/grpc-web").grpc;

var ExampleService = (function () {
  function ExampleService() {}
  ExampleService.serviceName = "v1.ExampleService";
  return ExampleService;
}());

ExampleService.ExampleCall1 = {
  methodName: "ExampleCall1",
  service: ExampleService,
  requestStream: false,
  responseStream: false,
  requestType: example_pb.ExampleMessage1,
  responseType: example_pb.ReturnType
};

ExampleService.ExampleCall2 = {
  methodName: "ExampleCall2",
  service: ExampleService,
  requestStream: false,
  responseStream: false,
  requestType: example_pb.ExampleMessage2,
  responseType: example_pb.ReturnType
};

exports.ExampleService = ExampleService;

function ExampleServiceClient(serviceHost, options) {
  this.serviceHost = serviceHost;
  this.options = options || {};
}

ExampleServiceClient.prototype.exampleCall1 = function exampleCall1(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(ExampleService.ExampleCall1, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

ExampleServiceClient.prototype.exampleCall2 = function exampleCall2(requestMessage, metadata, callback) {
  if (arguments.length === 2) {
    callback = arguments[1];
  }
  var client = grpc.unary(ExampleService.ExampleCall2, {
    request: requestMessage,
    host: this.serviceHost,
    metadata: metadata,
    transport: this.options.transport,
    debug: this.options.debug,
    onEnd: function (response) {
      if (callback) {
        if (response.status !== grpc.Code.OK) {
          var err = new Error(response.statusMessage);
          err.code = response.status;
          err.metadata = response.trailers;
          callback(err, null);
        } else {
          callback(null, response.message);
        }
      }
    }
  });
  return {
    cancel: function () {
      callback = null;
      client.close();
    }
  };
};

exports.ExampleServiceClient = ExampleServiceClient;

