/* eslint-disable */
/*Proudly generated by GenDocu.com*/
// package: v1
// file: example.proto

import * as example_pb from "./example_pb";
import {grpc} from "@improbable-eng/grpc-web";

type ExampleServiceExampleCall1 = {
  readonly methodName: string;
  readonly service: typeof ExampleService;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof example_pb.ExampleMessage1;
  readonly responseType: typeof example_pb.ReturnType;
};

type ExampleServiceExampleCall2 = {
  readonly methodName: string;
  readonly service: typeof ExampleService;
  readonly requestStream: false;
  readonly responseStream: false;
  readonly requestType: typeof example_pb.ExampleMessage2;
  readonly responseType: typeof example_pb.ReturnType;
};

export class ExampleService {
  static readonly serviceName: string;
  static readonly ExampleCall1: ExampleServiceExampleCall1;
  static readonly ExampleCall2: ExampleServiceExampleCall2;
}

export type ServiceError = { message: string, code: number; metadata: grpc.Metadata }
export type Status = { details: string, code: number; metadata: grpc.Metadata }

interface UnaryResponse {
  cancel(): void;
}
interface ResponseStream<T> {
  cancel(): void;
  on(type: 'data', handler: (message: T) => void): ResponseStream<T>;
  on(type: 'end', handler: (status?: Status) => void): ResponseStream<T>;
  on(type: 'status', handler: (status: Status) => void): ResponseStream<T>;
}
interface RequestStream<T> {
  write(message: T): RequestStream<T>;
  end(): void;
  cancel(): void;
  on(type: 'end', handler: (status?: Status) => void): RequestStream<T>;
  on(type: 'status', handler: (status: Status) => void): RequestStream<T>;
}
interface BidirectionalStream<ReqT, ResT> {
  write(message: ReqT): BidirectionalStream<ReqT, ResT>;
  end(): void;
  cancel(): void;
  on(type: 'data', handler: (message: ResT) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'end', handler: (status?: Status) => void): BidirectionalStream<ReqT, ResT>;
  on(type: 'status', handler: (status: Status) => void): BidirectionalStream<ReqT, ResT>;
}

export class ExampleServiceClient {
  readonly serviceHost: string;

  constructor(serviceHost: string, options?: grpc.RpcOptions);
  exampleCall1(
    requestMessage: example_pb.ExampleMessage1,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: example_pb.ReturnType|null) => void
  ): UnaryResponse;
  exampleCall1(
    requestMessage: example_pb.ExampleMessage1,
    callback: (error: ServiceError|null, responseMessage: example_pb.ReturnType|null) => void
  ): UnaryResponse;
  exampleCall2(
    requestMessage: example_pb.ExampleMessage2,
    metadata: grpc.Metadata,
    callback: (error: ServiceError|null, responseMessage: example_pb.ReturnType|null) => void
  ): UnaryResponse;
  exampleCall2(
    requestMessage: example_pb.ExampleMessage2,
    callback: (error: ServiceError|null, responseMessage: example_pb.ReturnType|null) => void
  ): UnaryResponse;
}

